<?php $title='About Mid City Home Restoration | Western New York';$description='Owner-operated, process-driven remodeling built to solve the contractor reliability problem in Western New York.';include __DIR__.'/../includes/header.php';
$stages=['Inquiry intake','Site visit','Scope writing','Client approval','Material procurement','Scheduling','Demo / prep','Rough-in coordination','Inspections','Finish work','Quality check','Punch list','Signature Finish Protocol','Project close'];
$areas=['Lockport','Buffalo','Niagara Falls','North Tonawanda','Tonawanda','Amherst','Cheektowaga','Depew','Lancaster','Williamsville','Kenmore','Grand Island','Wheatfield','Pendleton','Cambria','Wilson','Newfane','Lewiston','Youngstown','Ransomville','Medina'];
?>
<section class="page-hero about-hero"><div class="wrap"><p class="breadcrumbs">Home / About</p><p class="eyebrow">About Mid City Home Restoration</p><h1>Owner-operated. Process-driven. Built to solve the contractor reliability problem.</h1><p class="lead">Clear scopes, photo-verified stages, accountable communication, and a formal finish protocol for projects across Western New York.</p></div></section>
<section class="section white"><div class="wrap split"><div><p class="eyebrow">Why this company exists</p><h2>The contractor experience was broken. We built a better operating system.</h2><p>Homeowners were getting ghosted mid-project. Verbal quotes turned into surprise invoices. Timelines meant nothing. Quality checks only happened when the homeowner caught something wrong.</p><p>Mid City Home Restoration was built to work differently. Every project follows a documented process. Every scope is written before work begins. Every stage gets photo-verified. Every project closes through a formal quality gate—not a disappearing act.</p><p>This is not a company built on volume. It is built on doing the work correctly, documenting it, and standing behind it. Mid City Home Restoration operates as a division of URD Management Inc., based in Lockport, New York.</p></div><img class="rounded-image" src="/assets/images/renovation-hero.jpg" alt="Mid City Home Restoration project planning"></div></section>
<section class="section"><div class="wrap"><div class="section-head"><p class="eyebrow">The team</p><h2>Lean by design. Accountable by default.</h2><p>A small team means every person on the project understands the written scope, the quality standard, and who owns each next step.</p></div><div class="team-grid">
<article class="team-card"><img src="/assets/images/john-thomas.jpg" alt="John Thomas, CEO and Founder"><div><p class="eyebrow">CEO / Founder</p><h3>John Thomas</h3><p>Runs the business, manages every project scope, and handles client communication. If something goes sideways, John is the person responsible for fixing it.</p></div></article>
<article class="team-card"><img src="/assets/images/gary-tarr.jpg" alt="Gary Tarr, Lead Foreman and Co-Founder"><div><p class="eyebrow">Lead Foreman / Co-Founder</p><h3>Gary Tarr</h3><p>Leads field operations and manages day-to-day execution on job sites. Gary keeps the work aligned with the written scope and project timeline.</p></div></article>
<article class="team-card"><img src="/assets/images/jack.jpg" alt="Jack, painting and flooring specialist"><div><p class="eyebrow">Painting & Flooring Specialist</p><h3>Jack</h3><p>Handles painting and flooring installations across MHR projects. His finish work is what clients see last, so details and clean handoff matter.</p></div></article>
</div><div class="info-band"><strong>Licensed trade coordination</strong><p>MHR coordinates verified New York subcontractors for electrical, plumbing, and HVAC work. Licensed subcontractors must provide proof of active licensing and insurance before work begins.</p></div></div></section>
<section class="section dark"><div class="wrap"><div class="section-head"><p class="eyebrow">The 14-stage project lifecycle</p><h2>The process runs on every job, regardless of size.</h2></div><div class="lifecycle-grid"><?php foreach($stages as $i=>$stage):?><div class="lifecycle-item"><b><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></b><span><?=e($stage)?></span></div><?php endforeach;?></div></div></section>
<section class="section white"><div class="wrap split"><div><p class="eyebrow">The Signature Finish Protocol</p><h2>No project closes without a formal quality gate.</h2><p>The Signature Finish Protocol happens after construction is complete and before the project officially closes.</p><ul class="check-list"><li>Detailed walkthrough of all completed work with the client</li><li>Photo documentation of every finished area</li><li>Punch-list review and resolution of remaining items</li><li>Client sign-off confirming the work meets the written scope</li></ul></div><img class="rounded-image" src="/assets/images/bathroom-detail.jpg" alt="Finished Mid City bathroom project"></div></section>
<section class="section"><div class="wrap"><div class="section-head"><p class="eyebrow">What we stand on</p><h2>Standards that protect both sides.</h2></div><div class="value-grid"><article><h3>Documentation over memory</h3><p>Written scopes, photo-verified stages, and formal sign-offs. If it is not documented, it did not happen.</p></article><article><h3>Transparency over salesmanship</h3><p>You get the real scope, timeline, and cost. We do not lowball work and rely on preventable change orders later.</p></article><article><h3>Licensed trade compliance</h3><p>Work requiring licensed electrical, plumbing, or HVAC professionals is performed by verified New York trades.</p></article></div></div></section>
<section class="section white"><div class="wrap"><div class="section-head"><p class="eyebrow">Where we work</p><h2>21 communities within approximately 45 miles of Lockport.</h2><p>Staying local keeps our team close enough to manage work directly and respond quickly.</p></div><div class="area-cloud"><?php foreach($areas as $area):?><span><?=e($area)?></span><?php endforeach;?></div><p class="center-copy">Not sure whether your property is in our service area? Call <a class="text-link" href="tel:+18337366647">1-833-RENO-MHR</a>.</p></div></section>
<?php include __DIR__.'/../includes/reviews-section.php';?>
<section class="section"><div class="wrap form-shell"><?php $form_context='About page site-visit booking'; include __DIR__.'/../includes/lead-form.php';?></div></section>
<?php include __DIR__.'/../includes/footer.php';?>
