<?php $service=$lead['service']?:'General inquiry'; ?>
<!doctype html>
<html><body style="margin:0;background:#f2eee7;font-family:Arial,Helvetica,sans-serif;color:#17212b">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:34px 14px">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;margin:auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 12px 40px rgba(20,30,35,.08)">
<tr><td style="background:#102632;padding:34px;color:#fff"><div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#d0aa61">Project request received</div><h1 style="margin:10px 0 5px;font-family:Georgia,serif;font-size:30px;font-weight:normal">Thank you, <?=e($lead['name'])?></h1><p style="margin:0;color:#aebbc1;font-size:14px">Mid City Home Restoration</p></td></tr>
<tr><td style="padding:34px"><p style="font-size:16px;line-height:1.7;margin-top:0">We received your request for <strong><?=e($service)?></strong>. Our team will review the details and contact you to confirm the next step and schedule your site visit.</p>
<div style="padding:20px;background:#f8f4ed;border-radius:10px;border-left:5px solid #c8a45e;margin:24px 0"><div style="font-size:13px;color:#6d7478;text-transform:uppercase;letter-spacing:1px">Your submitted details</div><p style="margin:10px 0 4px"><strong>Phone:</strong> <?=e($lead['phone'])?></p><p style="margin:4px 0"><strong>Email:</strong> <?=e($lead['email'])?></p><p style="margin:4px 0"><strong>Preferred contact:</strong> <?=e($lead['contact_method']??'Phone')?></p><p style="margin:4px 0"><strong>Timeline:</strong> <?=e($lead['timeline']?:'Not specified')?></p></div>
<h2 style="font-family:Georgia,serif;font-size:22px;font-weight:normal;margin:28px 0 10px">What happens next</h2><p style="line-height:1.7">A project coordinator will review your scope, confirm that the property is within our Western New York service area, and contact you to arrange the site visit.</p>
<div style="margin-top:25px;padding:18px;background:#102632;color:#fff;border-radius:8px;text-align:center"><div style="font-size:13px;color:#d0aa61;text-transform:uppercase;letter-spacing:1px">Need immediate help?</div><p style="margin:8px 0 0"><a style="color:#fff;font-size:18px;font-weight:bold" href="tel:+18337366647">1-833-RENO-MHR</a></p></div>
<p style="margin:22px 0 0;color:#7a8388;font-size:12px">This confirmation was sent automatically from midcityhr.com. Reply to this email to contact our team.</p></td></tr>
</table></td></tr></table></body></html>
