<?php
if (!isset($slug)) $slug=basename(dirname($_SERVER['SCRIPT_FILENAME']));
require_once __DIR__.'/functions.php';
$service=service_by_slug($slug);if(!$service){http_response_code(404);exit('Not found');}
$title=$service['name'].' | Mid City Home Restoration';$description=$service['summary'];include __DIR__.'/header.php';
$isTurn=$slug==='property-management-turnas';
$deliverables=$isTurn?['Full unit paint and wall preparation','LVP, carpet, transition, and base-trim work','Fixture, hardware, detector, and appliance swaps','Compliance and inspection punch-list repairs','Deep-clean coordination and final readiness review','Multi-property and repeat-turn coordination']:$service['items'];
?>
<section class="hero service-hero" style="min-height:650px;--hero:url('<?=e($service['image'])?>')"><div class="wrap"><div><p class="breadcrumbs">Services / <?= $isTurn?'Property Managers':'Homeowners'?></p><p class="eyebrow"><?= $isTurn?'Fast, documented unit preparation':'Western New York remodeling service'?></p><h1><?=e($isTurn?'Property Management Turnovers':$service['name'])?></h1><p class="lead"><?=e($service['summary'])?></p><div class="hero-actions"><a class="button" href="#book"><?= $isTurn?'Schedule a Turnover Walkthrough':'Book Your Free Site Visit'?></a><a class="button outline" href="tel:+18337366647">Call 1-833-RENO-MHR</a></div><div class="trust-row"><span>Written Scope</span><span>Photo Updates</span><span>Clear Timeline</span><span><?= $isTurn?'Landlord Ready':'Formal Closeout'?></span></div></div></div></section>
<section class="section white"><div class="wrap split"><div><p class="eyebrow">Overview</p><h2><?= $isTurn?'Rental unit prep without dragging vacancy.':'A detailed scope before demolition or repair work begins.'?></h2><?php if($isTurn):?><p>Every vacant day costs money. Mid City Home Restoration helps landlords and property managers turn units faster with a clear scope, bundled repair tasks, and documentation from start to finish.</p><p>We handle move-out punch lists, wall repairs, paint, flooring, fixture and appliance swaps, compliance items, deep-clean coordination, and final readiness checks so the unit can be listed or occupied again.</p><?php else:?><p><?=e($service['intro'])?></p><p>We use the site visit to verify conditions, measure accurately, identify licensed-trade needs, and separate required work from optional upgrades. Your written proposal defines inclusions, exclusions, material assumptions, milestones, and closeout expectations.</p><?php endif;?></div><img class="rounded-image" src="<?=e($service['image'])?>" alt="<?=e($service['name'])?> project"></div></section>
<section class="section"><div class="wrap"><div class="section-head"><p class="eyebrow">Scope options</p><h2><?= $isTurn?'What we handle during turnovers':'What can be included in your project scope'?></h2></div><div class="scope-grid"><?php foreach($deliverables as $i=>$item):?><article><span><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><h3><?=e($item)?></h3><p><?= $isTurn?e(['Patch, prep, paint, trim touch-ups, doors, walls, and a clean turnover-ready finish.','Durable flooring replacement, damaged-area repair, transitions, and base trim.','Lighting, faucets, cabinet hardware, mirrors, smoke/CO detectors, and install support.','GFCI issues, railings, steps, doors, windows, drywall, safety items, and inspection lists.','Final walkthrough, readiness list, completion photos, and closeout notes.','Repeatable workflow for landlords and managers with multiple WNY units.'][$i]??'Documented completion under one coordinated scope.'):'The final written scope is tailored to the existing conditions, selected materials, and project goals.'?></p></article><?php endforeach;?></div></div></section>
<section class="section dark"><div class="wrap"><div class="section-head"><p class="eyebrow">Process</p><h2><?= $isTurn?'How a turnover works':'How your project moves from idea to closeout'?></h2></div><div class="process-cards"><article><b>01</b><h3><?= $isTurn?'Walk the unit':'Site assessment'?></h3><p>We document conditions, priorities, access, trade needs, and must-fix items.</p></article><article><b>02</b><h3>Written scope</h3><p>You receive defined work, pricing, assumptions, and timeline expectations before work starts.</p></article><article><b>03</b><h3><?= $isTurn?'Work sprint':'Coordinated build'?></h3><p>Tasks are sequenced efficiently with progress documentation and clear communication.</p></article><article><b>04</b><h3>Final closeout</h3><p>We complete the walkthrough, resolve punch items, and provide completion records.</p></article></div></div></section>
<section class="section white"><div class="wrap content-grid"><div><div class="section-head"><p class="eyebrow">Frequently asked questions</p><h2><?= $isTurn?'Property turnover questions':'Planning questions before work starts'?></h2></div><div class="faq-list"><details open><summary><?= $isTurn?'How fast can a unit be turned?':'How long will the project take?'?></summary><p><?= $isTurn?'Simple turnovers can often be completed in several days. Larger scopes involving flooring, compliance repairs, special-order materials, or licensed trades take longer.':'Timeline depends on verified site conditions, selections, material lead times, inspections, and licensed-trade coordination. We establish expectations in writing before scheduling.'?></p></details><details><summary><?= $isTurn?'Do you handle multiple units?':'Do you provide a written estimate?'?></summary><p><?= $isTurn?'Yes. We coordinate single-unit and multi-unit turnover scopes based on crew availability, access, and approval workflow.':'Yes. The site visit is used to prepare a written scope and estimate rather than relying on a verbal number or incomplete photos.'?></p></details><details><summary><?= $isTurn?'Can you document work for off-site owners?':'Who handles licensed trade work?'?></summary><p><?= $isTurn?'Yes. We provide photos, scope notes, and completion updates so owners and property managers can track progress remotely.':'Electrical, plumbing, and HVAC work requiring licensing is coordinated with verified New York licensed and insured subcontractors.'?></p></details></div></div><aside id="book"><?php $form_service=$service['name'];$form_context=$service['name'].' service-page booking';$form_title=$isTurn?'Schedule a Turnover Walkthrough':'Book Your Free Site Visit';include __DIR__.'/lead-form.php';?></aside></div></section>
<?php include __DIR__.'/reviews-section.php';?>
<?php include __DIR__.'/footer.php';?>
